# Generated by Django 4.1.6 on 2023-04-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ID_CLIENTE', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE_APELLIDO', models.CharField(max_length=150)),
                ('TELEFONO', models.CharField(max_length=15)),
                ('CEDULA', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('ID_FACTURAS', models.AutoField(primary_key=True, serialize=False)),
                ('MONTO_SOLICITADO', models.DecimalField(decimal_places=3, max_digits=10)),
                ('TASA', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CUOTAS', models.DecimalField(decimal_places=1, max_digits=5)),
                ('CUOTAS_MENSUALES', models.DecimalField(decimal_places=3, max_digits=10)),
                ('CAPITAL', models.DecimalField(decimal_places=3, max_digits=10)),
                ('INTERES', models.DecimalField(decimal_places=3, max_digits=10)),
                ('FECHA', models.DateField()),
                ('NOMBRE_APELLIDO', models.CharField(max_length=150)),
                ('TELEFONO', models.CharField(max_length=15)),
                ('CEDULA', models.CharField(max_length=20)),
                ('CLIENTE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialFacturas',
            fields=[
                ('ID_HISTORIALFACTURA', models.AutoField(primary_key=True, serialize=False)),
                ('MONTO_SOLICITADO', models.DecimalField(decimal_places=3, max_digits=10)),
                ('TASA', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CUOTAS', models.DecimalField(decimal_places=1, max_digits=5)),
                ('CUOTAS_MENSUALES', models.DecimalField(decimal_places=3, max_digits=10)),
                ('CAPITAL', models.DecimalField(decimal_places=3, max_digits=10)),
                ('INTERES', models.DecimalField(decimal_places=3, max_digits=10)),
                ('PAGO_REALIZADO', models.DecimalField(decimal_places=3, max_digits=10)),
                ('FECHA', models.DateField()),
                ('NOMBRE_APELLIDO', models.CharField(max_length=150)),
                ('TELEFONO', models.CharField(max_length=15)),
                ('CEDULA', models.CharField(max_length=20)),
                ('CLIENTE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.clientes')),
                ('FACTURA_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendAPI.facturas')),
            ],
        ),
    ]
