# Generated by Django 4.1.6 on 2023-04-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='PAGO_NUEVO',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='PAGO_REALIZADO',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historialfacturas',
            name='PAGO_NUEVO',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historialfacturas',
            name='PAGO_REALIZADO',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
