# Generated by Django 4.1.6 on 2023-04-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPI', '0002_facturas_pago_nuevo_facturas_pago_realizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='CAPITAL',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='CUOTAS',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='CUOTAS_MENSUALES',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='INTERES',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='MONTO_SOLICITADO',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='PAGO_NUEVO',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='PAGO_REALIZADO',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historialfacturas',
            name='CAPITAL',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historialfacturas',
            name='CUOTAS',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='historialfacturas',
            name='CUOTAS_MENSUALES',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historialfacturas',
            name='INTERES',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historialfacturas',
            name='MONTO_SOLICITADO',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historialfacturas',
            name='PAGO_NUEVO',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historialfacturas',
            name='PAGO_REALIZADO',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
